### ISSUE TITLE
Enable server sided configuration of attacks

### ISSUE THREAD

**Issue by bugraderre** [proofdock/chaos-middleware-python#11]
A service application attack shall be able to be attacked with a static configuration file. The specification is as follows:

```yaml
paths:
- path: /hello
  attacks:
    - type: delay
      value: '1'
      probability: '80'
    - type: exception
      value: BaseException
  methods:
    - GET
    - POST
- path: /api
  attacks:
    - type: delay
      value: '1'
    - type: exception
      value: BaseException
```
